version: '3.8'

services:
  db:
    build:
        context: ..
        dockerfile: ApplicationNet/sqlserver/Dockerfile
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - project2net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
        context: ..
        dockerfile: ApplicationNet/Dockerfile
    container_name: applicationnet
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Project2DB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    networks:
      - project2net

networks:
  project2net:

volumes:
  sqlserverdata:
